#file for pre-processing

"""
pre-processing.py file is responsible for operations in the time-domain for the input ECG signal.

The filter will be designed for some reasons:
- Removing noise
- Isolating the physiologically relevant ECG band
- Preparing the signal for: detection of R peaks and calculation of energy per beat
"""

import numpy as np
from scipy.signal import firwin, filtfilt, detrend

def bandpass_fir_filter(signal, fs, order, fc_low, fc_high, window="hanning"):

    """
    applying FIR bandpass filter to ECG signal.

    Parameters
    ----------
    signal : np.ndarray
        raw ECG signal (1D array).
    fs : float
        sampling frequency (Hz).
    lowcut : float
        lower cutoff frequency (Hz).
    highcut : float
        upper cutoff frequency (Hz).
    order : int
        order of the filter.

    Returns
    -------
    np.ndarray
        Bandpass filtered ECG signal.
    
    In addition, the signal will undergo some further pre-processing steps: to remove baseline wander and normalize the output signal to facilitate its implementation in the dashboard.
    """
        
    nyquist = fs / 2.0 
    normalized_cutoff = [fc_low/nyquist, fc_high/nyquist]

    #FIR filter design (using hanning window)
    #taps: number of filter coefficients
    taps = firwin(   #firwin is used to build the filter using some type of window
        numtaps=order+1, 
        cutoff=normalized_cutoff,
        pass_zero = False,
        window= "hann"
    )
    #zero-phase filtering, to remove the delay generated by the filter and preserve the position of the peaks
    filtered_signal = filtfilt(taps, 1.0, signal)

    return filtered_signal

def remove_baseline(signal, method="detrend"):
    """
    Removing baseline wander from ECG signal, a slow variation of the ECG signal baseline

    Parameters
    ----------
    signal : np.ndarray
        Input ECG signal.
    method : str
        Method for baseline removal ("detrend"). It removes DC/slow behavior and maintains fast variations.

    Returns
    -------
    np.ndarray
        Signal without baseline trend.
    """

    if method == "detrend":
        return detrend(signal)

    raise ValueError(f"Unknown baseline removal method: {method}")

def normalize_signal(signal, method="zscore"):
    """
    Normalize ECG signal amplitude, using some data preprocessing technique to transform the signal amplitude values ​​to a common scale, without distorting differences in the value ranges or losing information about outliers.

    Parameters
    ----------
    signal : np.ndarray
        Input ECG signal.
    method : str
        Normalization method (zscore) or (minmax).

    Returns
    -------
    np.ndarray
        Normalized signal.
    """

    if method == "zscore":
        mean = np.mean(signal)
        std = np.std(signal)
        return (signal - mean) / std

    elif method == "minmax":
        min_val = np.min(signal)
        max_val = np.max(signal)
        return (signal - min_val) / (max_val - min_val)

    else:
        raise ValueError(f"Unknown normalization method: {method}")
